#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
client:
 tls:
  enabled: false

 BCCSP:
     security:
      enabled: true
      default:
       provider: "PKCS11"
      hashAlgorithm: "SHA2"
      softVerify: true
      ephemeral: false
      level: 256
      pin: "98765432"
      label: "ForFabric"
      library: "/usr/lib/x86_64-linux-gnu/softhsm/libsofthsm2.so, /usr/lib/softhsm/libsofthsm2.so , /usr/lib/s390x-linux-gnu/softhsm/libsofthsm2.so, /usr/lib/powerpc64le-linux-gnu/softhsm/libsofthsm2.so, /usr/local/Cellar/softhsm/2.3.0/lib/softhsm/libsofthsm2.so"


 tcert:
  batch:
    size: 200

 logging:
  level: info

 keystore:
  path: /tmp/msp

 cryptoconfig:
  path: "$GOPATH/src/fabric-samples/basic-network/crypto-config"

 connection:
   timeout:
    peer:
     endorser: 3s
     eventHub: 3s
     eventReg: 3s
    orderer: 3s

# network provides a static definition of a Hyperledger Fabric network
 network:
  # list of ordering service nodes
  orderers:
   # orderer name
   orderer0:
    host: "localhost"
    port: 7050
    tls:
     # Certificate location absolute path
     certificate: "$GOPATH/src/fabric-samples/basic-network/crypto-config/ordererOrganizations/example.com/tlsca/tlsca.example.com-cert.pem"
     # For testing only: overrides the virtual host name of the authority
     serverHostOverride: "orderer.example.com"
  # ap of member organizations forming the network
  organizations:
    # Org1 name
    peerorg1:
      # Membership Service Provider ID for this organization
      mspID: "Org1MSP"
      # CA config defines the fabric-ca instance that issues identities for this org
      ca:
       # TLS secured connections with the CA
       tlsEnabled: false
       # CA name
       name: "ca.example.com"
       # CA URL. Note: https prefix required for TLS
       serverURL: "http://localhost:7054"
       # Configuration for mutual TLS with the CA
       tls:
        # Comma-Separated list of paths
        certfiles : "$GOPATH/src/fabric-samples/basic-network/crypto-config/peerOrganizations/org1.example.com/ca/ca.org1.example.com-cert.pem"
        client:
         keyfile: "$GOPATH/src/fabric-samples/basic-network/crypto-config/peerOrganizations/org1.example.com/ca/0e729224e8b3f31784c8a93c5b8ef6f4c1c91d9e6e577c45c33163609fe40011_sk"
         certfile: "$GOPATH/src/fabric-samples/basic-network/crypto-config/peerOrganizations/org1.example.com/ca/ca.org1.example.com-cert.pem"
      # Peers that are part of this organization
      peers:
       # Peer name
       peer0:
        host: "localhost"
        port: 7051
        eventHost: "localhost"
        eventPort: 7053
        primary: true
        tls:
         # Certificate location absolute path
         certificate: "$GOPATH/src/fabric-samples/basic-network/crypto-config/peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem"
         serverHostOverride: "peer0.org1.example.com"
